import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export async function getStaticProps() {
  const apiUrl = `${process.env.YOUTUBE_API}playlistItems?part=snippet&maxResults=50&playlistId=PLgRxtfPNGHyhEDLcWxN5VGbfU00iAU94-&key=${process.env.YOUTUBE_API_KEY}
  `;
  const res = await fetch(apiUrl);
  if (!res) return;
  const videoData = (await res.json()) as {};
  return {
    props: {
      videoData,
    },
  };
}

const Home: NextPage = ({ videoData }: any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Youtube Data API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Youtube Data APIを使ってみる🎥</h1>
        <ul className={styles.grid}>
          {videoData.items.map(({ id, snippet = {} }: any) => {
            const { title, thumbnails = {}, resourceId = {} } = snippet;
            const { medium } = thumbnails;
            return (
              <li key={id} className={styles.card}>
                <a
                  href={`https://www.youtube.com/watch?v=${resourceId.videoId}`}
                >
                  <p>
                    <img width="100%" src={medium.url} alt="サムネイル" />
                  </p>
                  <h3>{title}</h3>
                </a>
              </li>
            );
          })}
        </ul>
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image
              loader={({ src }) => src}
              src="/vercel.svg"
              alt="Vercel Logo"
              width={72}
              height={16}
            />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
